#!/bin/bash

while IFS= read -r number
do
    for (( i=2; i*i<=number; i++ )); do
        if (( number%i == 0 )); then
            echo "$number=$i*$((number/i))"
            break
        fi
    done
done < "$1"
