#!/bin/bash


is_prime() {
    local num=$1
    local sqrtnum=$(echo "sqrt($num)" | bc)
    for ((i=2; i<=sqrtnum; i++)); do
        if ((num % i == 0)); then
            return 1
        fi
    done
    return 0
}


num=$(cat $1)


for ((i=2; i*i<=num; i++)); do
    if ((num % i == 0)); then
        other=$((num/i))
        if is_prime $i && is_prime $other; then
            echo "$num=$i*$other"
            break
        fi
    fi
done
